apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
  - name: react-client
    image: pholawat-tle/react-client
    ports:
      - containerPort: 3000
