apiVersion: v1
kind: Service
metadata:
  name: client-nodeport-service
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - port: 80 
      # port exposed to other services
      targetPort: 3000
      # container port
      nodePort: 30000
      # port exposted to the outside world
